AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - '.git/**/*'
    - '.kitchen/**/*'
    - 'bin/**/*'

Chef/Style/CommentFormat:
  Enabled: true
Chef/Modernize/FoodcriticComments:
  Enabled: true
Chef/Style/FileMode:
  Enabled: true
Layout/TrailingEmptyLines:
  Enabled: true
Layout/TrailingWhitespace:
  Enabled: true
Chef/Correctness/InvalidVersionMetadata:
  Enabled: true
