---
inherit_from: .rubocop_todo.yml

# This is the RuboCop configuration used for Chef cookbooks
# It extends the default Cookstyle configuration with additional rules

plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - '.git/**/*'
    - 'cookbooks/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
  NewCops: enable

# Chef-specific rules
Chef/Deprecations:
  Enabled: true

Chef/Modernize:
  Enabled: true

Chef/RedundantCode:
  Enabled: true

Chef/Style:
  Enabled: true

# RSpec configuration for ChefSpec
RSpec:
  Language:
    Expectations:
      IncludeChain:
        Transformers:
          - LET_TRANSFORM

# Replace deprecated RSpec/FilePath with new split cops
RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/SpecFilePathSuffix:
  Enabled: false

# Performance optimizations
Performance:
  Enabled: true

# Layout customizations
Layout/LineLength:
  Max: 120
  Exclude:
    - '**/attributes/**/*.rb'
    - '**/metadata.rb'

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

# Naming conventions
Naming/FileName:
  Enabled: true
  Exclude:
    - '**/metadata.rb'
    - '**/Berksfile'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Policyfile.rb'
    - '**/Vagrantfile'

# Style preferences
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/NumericLiterals:
  Enabled: true
  MinDigits: 6

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

# Metrics
Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'test/**/*_test.rb'
    - 'resources/**/*.rb'
    - 'libraries/**/*.rb'

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Max: 300
  Exclude:
    - 'test/**/*'
    - 'libraries/**/*.rb'

# Chef-specific method names are allowed
Naming/PredicateName:
  Enabled: true
  ForbiddenPrefixes:
    - is_
    - has_
  AllowedMethods:
    - is_property_defined?
    - is_windows?
    - is_linux?

# Only include cops available in current Cookstyle
Chef/Style/AttributeKeys:
  AutoCorrect: true
  EnforcedStyle: symbols

Chef/Style/CommentFormat:
  Enabled: true
  
Chef/Style/CommentSentenceSpacing:
  Enabled: true
  
Chef/Style/FileMode:
  Enabled: true