name             'hbase'
maintainer       'Thomas Vincent'
maintainer_email 'thomasvincent@github.com'
license          'Apache-2.0'
description      'Installs/Configures Apache HBase'
version          '1.2.0'
chef_version     '>= 18.0'

# Current non-EOL platforms as of Chef Infra Client 18+
supports 'ubuntu', '>= 18.04'
supports 'debian', '>= 10.0'
supports 'redhat', '>= 7.0'
supports 'centos', '>= 7.0'
supports 'amazon', '>= 2.0'
supports 'oracle', '>= 7.0'
supports 'rocky', '>= 8.0'
supports 'almalinux', '>= 8.0'
supports 'fedora', '>= 36.0'
supports 'opensuseleap', '>= 15.0'
supports 'suse', '>= 12.0'
supports 'mac_os_x', '>= 12.0'
supports 'windows', '>= 10.0'
supports 'freebsd', '>= 13.0'

depends 'ark', '~> 5.0'

issues_url 'https://github.com/thomasvincent/chef-hbase-cookbook/issues'
source_url 'https://github.com/thomasvincent/chef-hbase-cookbook'